### ISSUE TITLE
Texture Pack

### ISSUE THREAD

**Issue by BlueLightningTR** [sypion/ODS-Upscaled#1]
When I try to open cogs page with texture pack it makes me crash what should I do?

**Comment by sypion** [comment]
Please attach a crash log.

**Comment by sypion** [comment]
I've encountered the same issue. Working on a solution now.

**Comment by BlueLightningTR** [comment]
Ok. Thanks.

**Comment by sypion** [comment]
Fixed the issue with v1.2. Download: https://upscaled.sypion.ml/
