### ISSUE TITLE
Telemarketer Textures

### ISSUE THREAD

**Issue by BlueLightningTR** [sypion/ODS-Upscaled#2]
Somehow telemarketer textures are same with two face texture and it's face look weird. http://prntscr.com/e0xahd

**Comment by toontownloony** [comment]
find file "twoface.jpg" and make sure it isn't a telemarketer head. If there isn't an existing file, check the existing cog head textures and make sure someone didnt accidentally replace the Twoface texture with the Telemarketer texture.

**Comment by sypion** [comment]
Update coming later in the afternoon in the repository to fix the Telemarketer texture issue.

**Comment by sypion** [comment]
Fixed the issue (and various others found in the `<>Code` tab).
